sudo: required
language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml

script:
  - mvn clean install -Dmaven.test.skip=true
